Bump auto-value from 1.5.3 to 1.7.4
Bumps [auto-value](https://github.com/google/auto) from 1.5.3 to 1.7.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/google/auto/releases">auto-value's releases</a>.</em></p>
<blockquote>
<h2>AutoValue 1.7.4</h2>
<ul>
<li>Stop the <code>LazyInit</code> annotation from getting shaded by Maven, so that AutoValue can find it on the classpath. (b484417)</li>
<li>Fixed handling of <code>@Nullable Optional&lt;T&gt; foo()</code> properties being set by <code>setFoo(@Nullable T)</code> setters. Now <code>setFoo(null)</code> results in <code>Optional.empty()</code>, not <code>null</code>. (d9d66ad)</li>
</ul>
<h2>AutoValue 1.7.3</h2>
<ul>
<li>Optionally copy annotations from the <code>@AutoValue.Builder</code> class to the generated subclass. (b22f969)</li>
<li>Drop unnecessary parentheses in AutoAnnotation <code>equals</code> and <code>hashCode</code> methods. (b9ba06a)</li>
<li>Fixed a problem when an <code>@AutoValue</code> class references types that are generated by other annotation processors. (2797d38)</li>
</ul>
<h2>AutoValue 1.7.2</h2>
<p>Only one change in this release:</p>
<ul>
<li>AutoValue is once again &quot;isolating&quot; for Gradle incremental compilation. (8e7515a)</li>
</ul>
<h2>AutoValue 1.7.1</h2>
<h2>New features</h2>
<ul>
<li>SerializableAutoValue extension. This can be used to serialize <code>@AutoValue</code> classes with properties of type <code>java.util.Optional</code>, even though <code>java.util.Optional</code> is not serializable, and it can also be configured to serialize other arbitrary types. Thanks to <a href="https://github.com/alvinlao">@alvinlao</a> for this contribution! (f91d2fe)</li>
<li>The logic for determining if we can make a BarBuilder out of a Bar has been generalized. For example, if your <code>@AutoValue</code> class <code>Foo</code> has a property <code>IntList ints()</code>, then your builder can have <code>IntListBuilder intsBuilder()</code>. Previously this worked if there was no <code>Foo.toBuilder()</code> method, or if <code>IntList</code> had its own <code>toBuilder()</code> method. Now it also works if it is possible to call <code>IntListBuilder.addAll(IntList)</code>. (6aeb44f)</li>
<li>AutoValue now allows boxed properties to be set from the corresponding primitive type, for example <code>Integer</code> from <code>int</code>. (2bbe506)</li>
</ul>
<h2>Behaviour changes</h2>
<ul>
<li>AutoValue now gives a warning if the static builder() method is inside the <code>@AutoValue.Builder</code> class instead of directly in the <code>@AutoValue</code> class. (fcccded)</li>
<li>AutoValue doesn't generate code or invoke extensions if it detects a problem, for example a mismatch between getters and setters. (ecb6032)</li>
<li>AutoOneOf factory methods for void values now have type parameters if the <code>@AutoOneOf</code> class does. (4ab1b53)</li>
<li>It is now a compilation error if a setter method in a builder has a parameter marked <code>@Nullable</code> when the corresponding property is not in fact <code>@Nullable</code>. Calling such a method with a null parameter already generated a NullPointerException at runtime. (bd7bed2)</li>
<li>The <code>@Memoized</code> annotation now has class-level retention, rather than source-level. (107694b)</li>
</ul>
<h2>Bug fixes</h2>
<ul>
<li>We fixed an issue with type checking of setter parameters in the presence of inheritance and generics. (e97d1f0)</li>
<li>We now generate a better <code>toString()</code> for arrays in AutoOneOf (0a7c049)</li>
</ul>
<h2>Miscellaneous</h2>
<ul>
<li>We added CompileWithEclipseTest, which checks that AutoValue works with ecj, the Eclipse compiler. (05e983c)</li>
</ul>
<h2>AutoValue 1.7</h2>
<p>This is the same as <code>1.7rc1</code>, with one small addition:</p>
<ul>
<li>Add a way for extensions to retrieve the name of the final AutoValue_Foo class. (4543619)</li>
</ul>
<p>Thanks to <a href="https://github.com/bryanstern">@bryanstern</a> for checking that the API changes for builder introspection do indeed work in a real extension.</p>
<h2>AutoValue 1.7rc1</h2>
<ul>
<li>Add an API to allow AutoValue extensions to find out about builders. (86f4563)</li>
<li>The generated AutoValue builder class is no longer final if there are extensions generating code. This means that extensions can subclass <code>Builder</code> to modify or extend its functionality. (49fbf55)</li>
<li>Property builders now work correctly when their actual return type is different from the corresponding property type because of type variable substitution. (7646889)</li>
<li>Allow <code>@AutoValue</code> getters to define properties that are not valid Java identifiers, for example <code>get1st()</code>. (6dfa04e)</li>
<li>Add a <code>propertyTypes()</code> method to <code>AutoValueExtension.Context</code>, to allow extensions to see the true type of every property. In preference to <code>properties().get(p).getReturnType()</code>, extensions should use <code>propertyTypes().get(p)</code>. (99ae134)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/google/auto/commit/c59110e29699bd2fcb3223cf306f62669ddfdc76"><code>c59110e</code></a> Set version number for auto-value-parent to 1.7.4.</li>
<li><a href="https://github.com/google/auto/commit/b48441776bb1eefe120dd4de5711e50209f46917"><code>b484417</code></a> Stop the LazyInit annotation from getting shaded by Maven, so that AutoValue ...</li>
<li><a href="https://github.com/google/auto/commit/d9d66ad60b4a09f74b7a9822fb347a1dbedf28f4"><code>d9d66ad</code></a> Fix handling of <code>@Nullable Optional\&lt;T&gt; foo()</code> properties being set by `setFoo...</li>
<li><a href="https://github.com/google/auto/commit/da84ef1fae38f2d72901c2b95674271e89600f28"><code>da84ef1</code></a> Tests related to e62e0abd2fbdfd2512c292ef95d4d152a5ca0691</li>
<li><a href="https://github.com/google/auto/commit/df5641b2340c8a437ab2c1c9579b97db27bc9fac"><code>df5641b</code></a> [ #HiltMigration ] Updating BasicAnnotationProcessor to support a String-base...</li>
<li><a href="https://github.com/google/auto/commit/e62e0abd2fbdfd2512c292ef95d4d152a5ca0691"><code>e62e0ab</code></a> Fix a problem with references to Factory classes in other packages.</li>
<li><a href="https://github.com/google/auto/commit/08f930a190737eca212da08ece6afa8e4287c336"><code>08f930a</code></a> Make the nested <a href="https://github.com/AutoValue">@AutoValue</a> class static otherwise you get the following error:</li>
<li><a href="https://github.com/google/auto/commit/32fdb09b437776951f724930afcc06f19f7e3f33"><code>32fdb09</code></a> Change links from google.github.io/guava to guava.dev, including making sure ...</li>
<li><a href="https://github.com/google/auto/commit/2f437b5a8276fdd4b4911a86e94ca61d16500180"><code>2f437b5</code></a> Change error reporting methods to use format strings.</li>
<li><a href="https://github.com/google/auto/commit/b22f969d63d7dc6f2163092637c2ba4c763f00bc"><code>b22f969</code></a> Copy annotations from <code>@AutoValue.Builder</code> to the generated <code>Builder</code> subclass.</li>
<li>Additional commits viewable in <a href="https://github.com/google/auto/compare/auto-value-1.5.3...auto-value-1.7.4">compare view</a></li>
</ul>
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.auto.value:auto-value&package-manager=maven&previous-version=1.5.3&new-version=1.7.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)

</details>

Fixes #201

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/compile-testing/pull/201 from google:dependabot/maven/com.google.auto.value-auto-value-1.7.4 a6255f5d81f64d1cbf88a36f8a4ece4612871e12
PiperOrigin-RevId: 337581372