Update plugins.
The update to maven-site-plugin fixes an error I saw during the release process:
- java.lang.NoClassDefFoundError: org/apache/maven/doxia/siterenderer/DocumentContent

The update to maven-javadoc-plugin does _not_ fix an error I saw during the release process:
- package com.sun.tools.javac.api is declared in module jdk.compiler, which does not export it to the unnamed module
So I worked around that one by building with JDK8 instead of JDK11. But we usually need to update maven-javadoc-plugin for some reason or another eventually, so let's just go with it.

Now that these plugins are listed explicitly, Dependabot should keep them up to date for us.

(Also, remove explicit specifications of "org.apache.maven.plugins." It is the default.)

(I made these changes already in a release branch, but now I'm making them "for good." https://github.com/google/compile-testing/commits/compile-testing-0.19)

RELNOTES=n/a
PiperOrigin-RevId: 338337384